core/urls.py
from django.contrib import admin
from django.urls import path, include
from store.views import home_view
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', home_view, name='home'),
    path('store/', include('store.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from .views import * 

app_name = 'store'

urlpatterns = [
    path('product/<int:id>/', product_detail, name='product-detail'),
    path('product-create/', product_create, name='product-create'),
    path('product-update/<int:id>', product_update, name='product-update'),
    path('product-delete/<int:id>', product_delete, name='product-delete'),
]

store/models.py
from django.db import models

class Brand(models.Model):
    name = models.CharField(max_length=30)
    logo = models.ImageField(upload_to='brands/')

    def __str__(self):
        return self.name
    

class Category(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    brand = models.ForeignKey(Brand, on_delete=models.CASCADE, related_name='products')
    categories = models.ManyToManyField(Category, related_name='products')

    def __str__(self):
        return self.name
    
    
class Color(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name
    

class Image(models.Model):
    url = models.ImageField(upload_to='products/', verbose_name="image")
    color = models.ForeignKey(Color, on_delete=models.CASCADE, related_name='images')
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='images')

    def __str__(self):
        return f'{self.product.name} | {self.color}'

store/forms.py
from django import forms
from .models import Product, Image

class ProductForm(forms.ModelForm):
    class Meta: 
        model = Product
        fields = ['name', 'price', 'brand', 'categories']

class ImageForm(forms.ModelForm):
    class Meta:
        model = Image
        fields = ['url', 'color']

store/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from .forms import ProductForm, ImageForm
from django.forms import inlineformset_factory

# Create your views here.
def home_view(request):
    context = {
        'products': Product.objects.all(),
        'brands': Brand.objects.all(),
        'categories': Category.objects.all(),
        'images': Image.objects.all(),
        'colors': Color.objects.all()
    }
    return render(request, 'index.html', context)


def product_detail(request, id):
    product = get_object_or_404(Product, id=id)
    context = {'product': product}
    return render (request, 'product-detail.html', context)


def product_create(request):
    ImageFormSet = inlineformset_factory(Product, Image, form=ImageForm, extra=1, can_delete=False)

    if request.method == 'POST':
        product_form = ProductForm(request.POST)
        image_formset = ImageFormSet(request.POST, request.FILES, instance=Product())

        if product_form.is_valid() and image_formset.is_valid():
            product = product_form.save()
            images = image_formset.save(commit=False)
            for image in images:
                image.product = product
                image.save()
            return redirect('home')  
    else:
        product_form = ProductForm()
        image_formset = ImageFormSet(instance=Product())

    context = {
        'view_name': 'Create Product',
        'product_form': product_form,
        'image_formset': image_formset,
    }

    return render(request, 'product-form.html', context)


def product_update(request, id):
    product = get_object_or_404(Product, id=id)
    ImageFormSet = inlineformset_factory(Product, Image, form=ImageForm, extra=0, can_delete=True)

    if request.method == 'POST':
        product_form = ProductForm(request.POST, instance=product)
        image_formset = ImageFormSet(request.POST, request.FILES, instance=product)

        if product_form.is_valid() and image_formset.is_valid():
            product = product_form.save()
            images = image_formset.save(commit=False)
            for image in images:
                image.product = product
                image.save()

            for image in image_formset.deleted_objects:
                image.delete()

            return redirect('home')
    else:
        product_form = ProductForm(instance=product)
        image_formset = ImageFormSet(instance=product)

    context = {
        'view_name': 'Update Product',
        'product_form': product_form,
        'image_formset': image_formset,
    }
    return render(request, 'product-form.html', context)


def product_delete(request, id):
    product = get_object_or_404(Product, id=id)

    if request.method == 'POST':
        product.delete()
        return redirect('home')
    
    return render(request, 'product-delete.html', {'product': product})

templates/index.html
{% extends "layout.html" %}

{% block title %}
    Home
{% endblock title %}

{% block main %}

<div class="heading">
    <div class="container">
        <article>
            <h5>BACKPACK COLLECTION</h5>
            <h1>Discover must-have <br> special offers and promos</h1>
            <button>Discover Now</button>
        </article>
    </div>
</div>

<div class="products-container">
    <div class="container">
        <div class="products-header">
            <div>
                <h4>Sort by latest</h4>
                <i class="fa-solid fa-caret-down"></i>
            </div>
            <div>
                <h4>Show filters</h4>
                <i class="fa-solid fa-bars-progress"></i>
            </div>
        </div>
        <div class="sidebar-products">
            <div class="sidebar">
                <div class="sortby">
                    <div class="sidebar-dropdown-btn">
                        <h4>Categories</h4>
                        <i class="fa-solid fa-angle-down"></i>
                    </div>
                    <hr>
                    <div class="sidebar-dropdown">
                        <ul class="categories">
                            {% for category in categories %}
                            <li>
                                <input type="checkbox" id="{{category.name}}">
                                <label for="{{category.name}}">{{category.name}} ({{category.products.count}})</label>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="sortby">
                    <div class="sidebar-dropdown-btn">
                        <h4>Brands</h4>
                        <i class="fa-solid fa-angle-down"></i>
                    </div>
                    <hr>
                    <div class="sidebar-dropdown">
                        <ul class="brand-logos">
                            {% for brand in brands %}
                            <li>
                                <img src="media/{{brand.logo}}" />
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="sortby">
                    <div class="sidebar-dropdown-btn">
                        <h4>Colors</h4>
                        <i class="fa-solid fa-angle-down"></i>
                    </div>
                    <hr>
                    <div class="sidebar-dropdown">
                        <ul class="colors">
                            {% for color in colors %}
                            <li>
                                <input type="radio" id="{{color.name}}" name="colors">
                                <label for="{{color.name}}">
                                    {{color.name.capitalize}} ({{color.images.count}})
                                    <div class="color-box" 
                                         style="background-color: {{color.name}}; 
                                         {% if color.name == 'white' %} 
                                         border: 1px black solid;
                                         {% endif %}">
                                    </div>
                                </label>
                            </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
            <div>
                <div class="products">
                    {% for product in products %}
                    <div class="product">
                        <div class="product-image">
                            {% if product.images.count == 0 %}
                                <div class="no-image">No Image</div>
                            {% else %}
                                <a href="{% url 'store:product-detail' product.id %}">
                                    <img src="media/{{product.images.first.url}}" />
                                </a>
                                {% if product.images.count > 1 %}
                                    <div class="product-colors">
                                        {% for image in product.images.all %}
                                            <div class="product-color" style="background-color: {{image.color.name}}"
                                                onclick="this.closest('.product-image').querySelector('img').src = 'media/{{image.url}}'">
                                            </div>
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            {% endif %}
                        </div>
                        <div class="product-desc">
                            <p class="product-category">
                                {% for category in product.categories.all|slice:":2" %}
                                <span>{{ category.name }}</span>{% if not forloop.last %}, {% endif %}
                                {% endfor %}
                            </p>
                            <a href="{% url 'store:product-detail' product.id %}" class="product-name">{{product.name}}</a>
                            <p class="product-price">${{product.price}}</p>
                            <hr>
                            <img class="product-brand-logo" src="media/{{ product.brand.logo }}">
                        </div>
                        <div class="product-icons">
                            <div class="icon-box">
                                <i class="fa-solid fa-magnifying-glass"></i>
                            </div>
                            <div class="icon-box">
                                <i class="fa-regular fa-heart"></i>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>

                <div class="pagination">
                    <i class="fa-solid fa-angle-left"></i>
                    <div class="links">
                        <a href="">1</a>
                        <a href="">2</a>
                        <a href="">3</a>
                        <a href="">4</a>
                    </div>
                    <i class="fa-solid fa-angle-right"></i>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock main %}

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>
        {% block title %}
            ShopAjax
        {% endblock title %}
    </title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css"
        integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
</head>

<body>
    <header>
        <div class="navbar">
            <div class="container">
                <nav>
                    <div class="nav-logo">
                        <img src="https://svgmix.com/uploads/5a27fe-envato.svg" />
                    </div>
                    <div class="nav-links">
                        <ul class="links">
                            <li><a href="#">Demos</a></li>
                            <li><a href="#">Features</a></li>
                            <li><a href="#">Works</a></li>
                            <li><a href="#">Blog</a></li>
                            <li><a href="#">Shop</a></li>
                            <li><a href="#">Pages</a></li>
                            <li class="dropdown-btn">
                                <a href="#">Products</a>
                                <ul class="dropdown">
                                    <li><a href="{% url 'home' %}">All Products</a></li>
                                    <li><a href="{% url 'store:product-create' %}">Create Product</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="nav-icons">
                        <i class="fa-solid fa-magnifying-glass"></i>
                        <i class="fa-regular fa-user"></i>
                        <i class="fa-regular fa-heart"></i>
                        <i class="fa-regular fa-bookmark"></i>
                    </div>
                </nav>
            </div>
        </div>
    </header>

    <main>
        {% block main %}
            Nothing here
        {% endblock main %}
    </main>

    <footer>
        <div class="container">
            <div class="footer-links">
                <div class="signup">
                    <h4>NEWSLETTER — SIGN UP</h4>
                    <p>Be the first to know about special offers, new product launches, and events.</p>
                    <form>
                        <input type="text" placeholder="Your Email">
                        <button>Subscribe</button>
                    </form>
                </div>
                <div class="links">
                    <div>
                        <h4>Shop</h4>
                        <ul>
                            <li>Shop All</li>
                            <li>Woman Collection</li>
                            <li>Man Collection</li>
                            <li>Accessories</li>
                            <li>New Arrivals</li>
                            <li>Latest Collection</li>
                            <li>Gift Card</li>
                            <li>Top Sellers</li>
                        </ul>
                    </div>
                    <div>
                        <h4>CUSTOMERS</h4>
                        <ul>
                            <li>Faqs</li>
                            <li>Shipping</li>
                            <li>Returns</li>
                            <li>Terms</li>
                            <li>Contact Us</li>
                            <li>Privacy</li>
                        </ul>
                    </div>
                    <div>
                        <h4>CONTACT US</h4>
                        <ul>
                            <li>help@yourwebsite.com</li>
                            <li>1-888-625-80644</li>
                            <li>1-888-912-83735</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <hr>
        <div class="container">
            <div class="last">
                <p>© 2024 Uncode. All rights reserved</p>
                <div class="icons">
                    <i class="fa-brands fa-facebook"></i>
                    <i class="fa-brands fa-twitter"></i>
                    <i class="fa-brands fa-youtube"></i>
                    <i class="fa-brands fa-instagram"></i>
                </div>
            </div>
        </div>
    </footer>

    <script src="{% static 'js/dropdown.js' %}"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
    {% block scripts %}{% endblock scripts %}
</body>

</html>

templates/product-create.html
{% extends "layout.html" %}

{% block title %}
    Create Product
{% endblock title %}

{% block main %}

<div class="container">
    <h1>Create Product</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ product_form}}
        <div id="formset">
            {{ image_formset.management_form }}
            {% for image_form in image_formset %}
                <div class="form-row">
                    {{ image_form }}
                </div>
            {% endfor %}
        </div>
        <button class="form-btn" type="button" id="add-image">Add another image</button>
        <button class="form-btn" type="submit">Save</button>
    </form>

    <!-- Empty form template for new images -->
    <div id="empty-form" style="display: none;">
        <div class="form-row">
            {{ image_formset.empty_form }}
        </div>
    </div>
</div>

{% endblock main %}


{% block scripts %}

<script>
    $('#id_categories').select2();
</script>

<script>
    $(document).ready(function() {
        let formIdx = $('#id_images-TOTAL_FORMS').val();
        $('#add-image').click(function() {
            $('#formset').append($('#empty-form').html().replace(/__prefix__/g, formIdx));
            formIdx++;
            $('#id_images-TOTAL_FORMS').val(formIdx);
        });
    });
</script>

{% endblock scripts %}

templates/product-delete.html
{% extends "layout.html" %}

{% block title %}
    Delete Product
{% endblock title %}

{% block main %}

<div class="container">
  <h1>Delete Product</h1>
  <p>Are you sure you want to delete "{{ product.name }}"?</p>

  <form method="post">
    {% csrf_token %}
    <a href="{% url 'store:product-detail' product.id %}"><button class="form-btn" type="button">Cancel</button></a>
    <button class="form-btn" type="submit" >Confirm</button>
  </form>
</div>

{% endblock main %}

templates/product-detail.html
{% extends "layout.html" %}

{% block title %}
    Product Details
{% endblock title %}

{% block main %}

<div class="container">
    <div class="product-detail">
        <div class="product-image">
            {% if product.images.count == 0 %}
                <div class="no-image">No Image</div>
            {% else %}
                <img src="/media/{{product.images.first.url}}" />
            {% endif %}
        </div>
        <div class="product-desc">
            <h1 class="product-name">{{product.name}}</h1>
            <h1 class="product-price">${{product.price}}</h1>
            <p class="product-category">
                Category:
                {% for category in product.categories.all %}
                    <span>{{ category.name }}</span>{% if not forloop.last %}, {% endif %}
                {% endfor %}
            </p>
            {% if product.images.count > 1 %}
                <div class="product-images">
                    {% for image in product.images.all %}
                        <img src="/media/{{image.url}}" onclick="this.closest('.product-detail').querySelector('.product-image img').src = '/media/{{image.url}}'">
                    {% endfor %}
                </div>
            {% endif %}
            <img class="product-brand-logo" src="/media/{{ product.brand.logo }}">
        </div>
        <div class="product-icons">
            <div class="icon-box">
                <i class="fa-solid fa-magnifying-glass"></i>
            </div>
            <div class="icon-box">
                <i class="fa-regular fa-heart"></i>
            </div>
        </div>
    </div>

    <a href="{% url 'store:product-update' product.id %}"><button class="form-btn">Update Product</button></a>
    <a href="{% url 'store:product-delete' product.id %}"><button class="form-btn">Delete Product</button></a>
</div>
{% endblock main %}

templates/product-form.html
{% extends "layout.html" %}

{% block title %}
    {{ view_name }}
{% endblock title %}

{% block main %}

<div class="container">
    <h1>{{ view_name }}</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ product_form}}
        <div id="formset">
            {{ image_formset.management_form }}
            {% for image_form in image_formset %}
                <div class="form-row">
                    {{ image_form }}
                </div>
            {% endfor %}
        </div>
        <button class="form-btn" type="button" id="add-image">Add another image</button>
        <button class="form-btn" type="submit">Save</button>
    </form>

    <!-- Empty form template for new images -->
    <div id="empty-form" style="display: none;">
        <div class="form-row">
            {{ image_formset.empty_form }}
        </div>
    </div>
</div>

{% endblock main %}


{% block scripts %}

<script>
    $('#id_categories').select2();
</script>

<script>
    $(document).ready(function() {
        let formIdx = $('#id_images-TOTAL_FORMS').val();
        $('#add-image').click(function() {
            $('#formset').append($('#empty-form').html().replace(/__prefix__/g, formIdx));
            formIdx++;
            $('#id_images-TOTAL_FORMS').val(formIdx);
        });
    });
</script>

{% endblock scripts %}